apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
  labels:
    name: mysql-exporter
  name: mysql-exporter
spec:
  ports:
    - port: 9104
      targetPort: 9104
  selector:
    name: mysql-exporter
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mysql-exporter
  name: mysql-exporter-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-exporter
    spec:
      containers:
      - image: prom/mysqld-exporter
        name: mysql-exporter
        ports:
        - name: mysql-exporter
          containerPort: 9104
        env:
        - name: DATA_SOURCE_NAME
          value: "admin:YOUR_PASSWD@tcp(YOUR HOST:YOUR_PORT)/ycsb"
